import React, { useState } from "react";
import { Terminal, Copy, Check, Share2, Sparkles, Code, Server, BookmarkCheck } from "lucide-react";
import { encodeConfigToQuery } from "../utils/math.js";

export default function ExportTerminal({ config, computedSteps }) {
  const [activeTab, setActiveTab] = useState("css");
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);

  // Computed sharing URL
  const getSharingUrl = () => {
    const query = encodeConfigToQuery(config);
    return `${window.location.origin}${window.location.pathname}?${query}`;
  };

  // Generate RAW CSS variables code block
  const generateRawCssCode = () => {
    let output = `/* 🎯 FLUID TYPOGRAPHY CUSTOM VARIABLES - GENERATED BY THE MATH ENGINE */\n`;
    output += `:root {\n`;
    output += `  /* Viewport Scaling Gate boundaries */\n`;
    output += `  --min-viewport: ${config.minViewport}px;\n`;
    output += `  --max-viewport: ${config.maxViewport}px;\n`;
    output += `  --base-ratio: ${config.ratio === 0 ? (config.customRatio || 1.25) : config.ratio};\n\n`;

    output += `  /* Computed clamp equations */\n`;
    computedSteps.forEach((step) => {
      output += `  --font-size-${step.name}: ${step.clampString};\n`;
    });
    output += `}\n\n`;
    output += `/* Example utilization */\n`;
    output += `body {\n`;
    output += `  font-family: '${config.selectedFont}', sans-serif;\n`;
    output += `  font-size: var(--font-size-base);\n`;
    output += `}\n\n`;
    output += `h1 {\n`;
    output += `  font-size: var(--font-size-4xl);\n`;
    output += `  font-weight: 800;\n`;
    output += `}`;
    return output;
  };

  // Generate Tailwind v4 CSS @theme declarations and Tailwind v3 configuration
  const generateTailwindCode = () => {
    let output = `/* Tailwind CSS v4 Theme Import Configuration */\n`;
    output += `@import "tailwindcss";\n\n`;
    output += `@theme {\n`;
    output += `  --font-sans: "${config.selectedFont}", sans-serif;\n\n`;
    output += `  /* Register custom fluid scale levels */\n`;
    computedSteps.forEach((step) => {
      output += `  --text-${step.name}: ${step.clampString};\n`;
    });
    output += `}\n\n`;
    output += `/* Legacy Tailwind CSS v3 Theme Extend configuration (tailwind.config.js) */\n`;
    output += `module.exports = {\n`;
    output += `  theme: {\n`;
    output += `    extend: {\n`;
    output += `      fontFamily: {\n`;
    output += `        sans: ['${config.selectedFont}', 'sans-serif'],\n`;
    output += `      },\n`;
    output += `      fontSize: {\n`;
    computedSteps.forEach((step) => {
      output += `        '${step.name}': '${step.clampString}',\n`;
    });
    output += `      }\n`;
    output += `    }\n`;
    output += `  }\n`;
    output += `};`;
    return output;
  };

  // Generate Styled Components JS declaration block
  const generateStyledComponentsCode = () => {
    let output = `import styled, { createGlobalStyle } from 'styled-components';\n\n`;
    output += `export const FluidTheme = {\n`;
    output += `  typography: {\n`;
    output += `    fontFamily: "'${config.selectedFont}', sans-serif",\n`;
    computedSteps.forEach((step) => {
      output += `    size_${step.name}: "${step.clampString}",\n`;
    });
    output += `  }\n`;
    output += `};\n\n`;
    output += `export const GlobalTypography = createGlobalStyle\`\n`;
    output += `  body {\n`;
    output += `    font-family: \${props => props.theme.typography.fontFamily};\n`;
    output += `    font-size: \${props => props.theme.typography.size_base};\n`;
    output += `  }\n`;
    output += `\`;\n\n`;
    output += `export const FluidHeroHeading = styled.h1\`\n`;
    output += `  font-size: \${props => props.theme.typography.size_5xl};\n`;
    output += `  line-height: 1.1;\n`;
    output += `  font-weight: 800;\n`;
    output += `\`;`;
    return output;
  };

  const getActiveCode = () => {
    switch (activeTab) {
      case "css":
        return generateRawCssCode();
      case "tailwind":
        return generateTailwindCode();
      case "styled":
        return generateStyledComponentsCode();
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const copyShareLink = () => {
    const link = getSharingUrl();
    navigator.clipboard.writeText(link);
    setShared(true);
    setTimeout(() => setShared(false), 2500);
  };

  // Mock highlighting utilizing manual replacement for CSS syntax lookups
  const highlightTokenText = (text) => {
    return text.split("\n").map((line, idx) => {
      // Very simple token matching styling for CSS-like blocks to render beautifully
      if (line.startsWith("/*") || line.startsWith("  /*") || line.startsWith("//")) {
        return <span key={idx} className="text-gray-400 block italic leading-relaxed">{line}</span>;
      }
      if (line.includes(":root") || line.includes("@theme") || line.includes("module.exports")) {
        return <span key={idx} className="text-pink-400 font-bold block">{line}</span>;
      }
      
      // Highlight variables and clamp keywords
      let renderedLine = <span className="text-emerald-300">{line}</span>;
      if (line.includes("clamp(")) {
        const parts = line.split("clamp(");
        renderedLine = (
          <span>
            <span className="text-gray-300">{parts[0]}</span>
            <span className="text-yellow-300">clamp(</span>
            <span className="text-blue-300">{parts[1].slice(0, -2)}</span>
            <span className="text-yellow-300">)</span>
            <span className="text-purple-400">;</span>
          </span>
        );
      } else if (line.includes(": ")) {
        const parts = line.split(": ");
        renderedLine = (
          <span>
            <span className="text-sky-300">{parts[0]}</span>
            <span className="text-purple-400">: </span>
            <span className="text-[#ADFA1D]">{parts[1]}</span>
          </span>
        );
      }
      return <span key={idx} className="block whitespace-pre">{renderedLine}</span>;
    });
  };

  return (
    <div className="bg-[#121212] border-4 border-black text-white p-6 rounded-none shadow-[6px_6px_0px_0px_#000000] flex flex-col gap-5 font-mono">
      
      {/* Code window control bar */}
      <div className="flex flex-wrap items-center justify-between border-b-2 border-gray-800 pb-4">
        <div className="flex items-center gap-2">
          <Terminal className="w-5 h-5 text-[#ADFA1D]" />
          <h3 className="font-sans font-black tracking-wider text-sm text-[#ADFA1D] uppercase">
            COMPILER TERMINAL (V1.2)
          </h3>
        </div>

        {/* Sync tabs */}
        <div className="flex gap-1.5 mt-2 sm:mt-0">
          <button
            onClick={() => setActiveTab("css")}
            className={`px-3 py-1 text-xs font-bold transition-all ${
              activeTab === "css"
                ? "bg-[#ADFA1D] text-black"
                : "bg-gray-900 border border-gray-800 hover:border-[#ADFA1D] text-gray-400 hover:text-white"
            }`}
          >
            Custom css
          </button>
          <button
            onClick={() => setActiveTab("tailwind")}
            className={`px-3 py-1 text-xs font-bold transition-all ${
              activeTab === "tailwind"
                ? "bg-[#ADFA1D] text-black"
                : "bg-gray-900 border border-gray-800 hover:border-[#ADFA1D] text-gray-400 hover:text-white"
            }`}
          >
            Tailwind config
          </button>
          <button
            onClick={() => setActiveTab("styled")}
            className={`px-3 py-1 text-xs font-bold transition-all ${
              activeTab === "styled"
                ? "bg-[#ADFA1D] text-black"
                : "bg-gray-900 border border-gray-800 hover:border-[#ADFA1D] text-gray-400 hover:text-white"
            }`}
          >
            Styled theme
          </button>
        </div>
      </div>

      {/* Compiler main code board */}
      <div className="relative bg-[#1A1A1A] border-2 border-gray-800 p-4 h-96 overflow-y-auto font-mono text-[11px] leading-relaxed custom-scrollbar shadow-inner">
        
        {/* Absolute copy button */}
        <div className="absolute top-2 right-2 z-10">
          <button
            onClick={() => copyToClipboard(getActiveCode())}
            className="flex items-center gap-1 bg-black hover:bg-gray-900 border-2 border-gray-800 text-white rounded-none px-3 py-1 text-[10px] font-bold shadow-[2px_2px_0_0_rgba(173,250,29,0.3)] hover:shadow-[2px_2px_0_0_rgba(173,250,29,1)] transition-all active:translate-y-0.5"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                COPIED! FR FR!
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-gray-400" />
                COPY BLOCK
              </>
            )}
          </button>
        </div>

        {/* Highlighted text compiler body */}
        <div className="pt-8">
          {highlightTokenText(getActiveCode())}
        </div>
      </div>

      {/* Share & Save System Deck */}
      <div className="border-t-2 border-gray-800 pt-4 flex flex-col md:flex-row gap-4 items-center justify-between">
        <div className="text-xs text-gray-400 leading-relaxed max-w-md">
          <span className="text-[#ADFA1D] block mb-1 font-bold">⚡ NO CAP STORAGE PERSISTENCE</span>
          This playground is modularly built out. Send this share link to sync parameters instantly with other creators.
        </div>

        <button
          onClick={copyShareLink}
          className="w-full md:w-auto flex items-center justify-center gap-2 bg-[#C084FC] hover:bg-[#a855f7] text-black border-2 border-black font-sans font-black text-xs uppercase px-5 py-2.5 shadow-[4px_4px_0_0_#FFF] hover:shadow-[4px_4px_0_0_#ADFA1D] active:translate-y-0.5 transition-all"
        >
          {shared ? (
            <>
              <BookmarkCheck className="w-4 h-4 text-white animate-bounce" />
              LINK COPIED! BET!
            </>
          ) : (
            <>
              <Share2 className="w-4 h-4" />
              GENERATE SHARE URL
            </>
          )}
        </button>
      </div>

    </div>
  );
}
